find_package(ROOT REQUIRED RIO)

list(APPEND CMAKE_PREFIX_PATH $ENV{ROOTSYS})
list(APPEND CMAKE_PREFIX_PATH ${ROOTSYS})

message(STATUS "Using ROOT: ${ROOT_VERSION} <${ROOT_CONFIG}>")

list(APPEND PROJECT_INCLUDE_DIRECTORIES ${ROOT_INCLUDE_DIR} ${ROOT_INCLUDE_DIRS})

include(${ROOT_USE_FILE})
